### ISSUE TITLE
Provide initial guess of variables without warmstart

### ISSUE THREAD

**Issue by stumarcus314** [jump-dev/Convex.jl#233]
Is it possible to provide an initial guess of the unknowns when using Convex.jl to solve a convex optimization problem, without using a warmstart from a previous solve? For example, in the sample code I want to use a function like JuMP's setvalue to provide an initial guess of the unknown variable x.

using Convex
m = 4;  n = 5; A = randn(m, n); b = randn(m, 1);
x = Variable(n);
setvalue(x,ones(n,1)) # setvalue does not work for Convex.jl. Is there a work-around?
problem = minimize(sumsquares(A * x - b), [x >= 0])
solve!(problem)

**Comment by ericphanson** [comment]
This is very late, but one workaround is to just set `x.value = ones(n)`. When you call `solve!` with `warmstart=true` it will give you a warning:
```julia
julia> solve!(problem, SCSSolver(); warmstart = true)
┌ Warning: Unable to use cached solution to warmstart problem.
│                 (Perhaps this is the first time you're solving this problem?)
│                 Warmstart may be ineffective.
```
but looking at the code, it should indeed use the value you placed in `x.value` to populate that variable. When you solve with `warmstart=true` without having solved the problem previously, all variables you don't set with `x.value = ....` with be warmstarted with a value of zero though, and likewise if Convex internally generates any auxillary variables when converting your problem to a standard form, it will set them to zero too (even if they should be able to be determined by the variables you did set a value for). Also, of course, the solver and its MathProgBase interface need to be programmed to use the warmstarted values (this I don't know about).

I think if/when we switch to MathOptInterface that would be a good opportunity to take a second look at this API and see if we can have a cleaner version.

**Comment by odow** [comment]
This now works. But it just needs documenting.
