### ISSUE TITLE
Strange performance issue

### ISSUE THREAD

**Issue by HFriberg** [jump-dev/Convex.jl#246]
This is my first attempt to use Convex.jl so I am not sure what to expect, but I am seeing quite bad performance.

Running `julia test.jl` on my `test.jl` file shown here:
```
using Convex
include("batchdes.jl")     # see https://github.com/mlubin/MICPExperiments/blob/master/MINLPLIB2/batchdes.jl
include("clay0203h.jl")    # see https://github.com/mlubin/MICPExperiments/blob/master/MINLPLIB2/clay0203h.jl

function main()
  @time batchdes()
  @time clay0203h()
  nothing
end
@time main()
```
shows 
```
  0.184365 seconds (230.53 k allocations: 11.837 MiB)
  0.001554 seconds (7.20 k allocations: 419.797 KiB)
 45.604998 seconds (9.00 M allocations: 510.333 MiB, 0.88% gc time)
```
so there is a huge cost in `main()` not reflected by the individual function calls. Changing `@time` to `@profile` does not capture the hidden cost. Wrapping the whole script in a `@profile begin ... end` block, however, shows exactly one line to be the culprit, namely:
https://github.com/JuliaLang/julia/blob/648c3690a5a22ccccaa5d47934497b151628d530/base/compiler/ssair/domtree.jl#L86.

This strange performance issue makes Convex.jl pretty unusable to me. The two files used here are among the smallest in MICPExperiments, and the hidden cost is even bigger (>10min) for just slightly larger instances such as `batchs101006m.jl`.

What to do?

**Setup**
I am using Convex v0.8.0 according to Pkg.installed(), and in this environment
```
Julia Version 1.0.1
Commit 0d713926f8 (2018-09-29 19:05 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2470 v2 @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, ivybridge)
```

**Comment by HFriberg** [comment]
So I tried replacing `clay0203h` in the `test.jl` file with the slightly larger `batchs101006m` instance (see https://github.com/mlubin/MICPExperiments/blob/master/MINLPLIB2/batchs101006m.jl) and got the absolutely insane results:
```
  0.476228 seconds (226.66 k allocations: 11.620 MiB)
  0.004475 seconds (18.31 k allocations: 978.172 KiB)
3195.833704 seconds (30.87 M allocations: 3.862 GiB, 0.11% gc time)
```

**Comment by ararslan** [comment]
What happens if you use Julia 0.6 with v0.7.0 of Convex? And which solver are you using for this?

**Comment by HFriberg** [comment]
Ahh, is the choice of solver affecting problem setup? I was not thinking of that since I am only using Convex.jl to construct instances to be written in the CBF file format. Let me see, I have SCS listed as the default solver. Will do more experiments another day.

**Comment by ararslan** [comment]
The solver might not make a difference at all, I was just wondering, since it's another moving piece in Convex.

**Comment by HFriberg** [comment]
In the original test with `batchdes` and `clay0203h`, Julia v0.6.4 with Convex v0.7.0 gives 
```
  0.301253 seconds (63.29 k allocations: 3.482 MiB)
  0.026721 seconds (11.12 k allocations: 600.807 KiB)
  3.590112 seconds (855.90 k allocations: 45.891 MiB, 3.59% gc time)
```
With `batchdes` and `batchs101006m` I get:
```
  0.311981 seconds (62.73 k allocations: 3.434 MiB)
  0.040580 seconds (31.62 k allocations: 1.585 MiB)
 20.624354 seconds (1.95 M allocations: 98.735 MiB, 0.70% gc time)
```
Regression has surely happened in either the Julia compiler or Convex.

**Comment by HFriberg** [comment]
I see splatting used all around the Convex.jl code (example: https://github.com/JuliaOpt/Convex.jl/blob/master/src/atoms/affine/add_subtract.jl#L101), and have heard that this it not optimized code. Could be what's heavy on the compiler?

**Comment by ararslan** [comment]
Here's what I get on my machine:

Julia 1.0.2, official binaries:
```
  0.109220 seconds (217.04 k allocations: 11.162 MiB)
  0.000870 seconds (7.22 k allocations: 420.938 KiB)
 27.539773 seconds (9.10 M allocations: 515.455 MiB, 1.02% gc time)
```
Julia 1.1.0-DEV.653 (current master), source build:
```
  0.113538 seconds (217.93 k allocations: 11.263 MiB, 4.59% gc time)
  0.001230 seconds (7.25 k allocations: 421.266 KiB)
 10.306904 seconds (6.00 M allocations: 261.128 MiB, 1.16% gc time)
```
So the situation is improved on Julia master, which means 1.1 will achieve better performance here, but that doesn't help 1.0. That suggests to me that the performance issue has more to do with Julia itself rather than with Convex. (Though that's not to say Convex couldn't be doing things better.) It would be good to identify what in particular provided the improvements so that it can be backported if possible to 1.0.3.

Regarding splatting, it depends. There is a performance penalty for splatting large iterables, but for smaller ones it shouldn't make a big difference. IIRC the cutoff was at one point 16, but I could be misremembering.

**Comment by odow** [comment]
Whatever the problem was, it seems to be fixed:
```Julia
julia> using Convex

julia> include("batchdes.jl")     # see https://github.com/mlubin/MICPExperiments/blob/master/MINLPLIB2/batchdes.jl
batchdes (generic function with 1 method)

julia> include("clay0203h.jl")    # see https://github.com/mlubin/MICPExperiments/blob/master/MINLPLIB2/clay0203h.jl
clay0203h (generic function with 1 method)

julia> function main()
         @time batchdes()
         @time clay0203h()
         nothing
       end
main (generic function with 1 method)

julia> @time main()
  0.068625 seconds (83.64 k allocations: 5.188 MiB, 98.88% compilation time)
  0.022344 seconds (6.87 k allocations: 476.406 KiB, 95.73% compilation time)
  0.109144 seconds (95.43 k allocations: 5.929 MiB, 81.77% compilation time)

julia> @time main()
  0.000096 seconds (341 allocations: 23.719 KiB)
  0.000579 seconds (3.39 k allocations: 218.859 KiB)
  0.000951 seconds (3.78 k allocations: 246.266 KiB)
```
