### ISSUE TITLE
Call for test problems with dual values

### ISSUE THREAD

**Issue by ericphanson** [jump-dev/Convex.jl#290]
I have been thinking about how to update Convex to MathOptInterface (https://github.com/JuliaOpt/Convex.jl/issues/262). While it's not so complicated, I am worried about introducing subtle bugs. In particular, I think retrieving dual variables from MathOptInterface will require slightly more changes to the code than for primal values. This isn't so bad except for the fact that only 5 of our 800+ or so tests are testing dual values, and they are all for affine problems.

Thus, I'd like to ask if anyone has problems for which they know the optimal dual values (preferably not because Convex.jl solved it, but rather some independent method such as another library or solving it analytically). If you want to just post them here, I don't mind turning them into tests and making a pull request.

I suppose another option is to try to incorporate tests from another DCP library (assuming the licenses are ok). But I don't know if there's an easy way to automate that or not.

**Comment by ranocha** [comment]
I would like to think about and contribute test problems in PRs (in order to get to know the code etc.). After having a look at the currently open PRs, it seems that the test infrastructure is going to be changed quite a lot. How shall new test problems be contributed at the moment:
1. PR to `master`?
2. PR to one of the open PRs #328, #330?
3. Just think about the problems and add them later when #328, #330 are merged?

**Comment by ericphanson** [comment]
That’s awesome! Getting some more tests for dual variables would be really great. 

Something I realized since making this issue is that Convex only supports dual variables for a few constraints— I actually don’t know which off the top of my head, but definitely not SDP constraints (yet).

I think it would be good to verify the current version of Convex (master / #328) passes tests before sending them to the MOI version (#330).

So I’d say make the PR against either master or #328. We will have to migrate them to #328 before merging it, but it’s really not too hard to do so (I moved all 800 tests to #328, so I know it’s not too bad!). So I’d say whichever you feel more comfortable with.

If you do go for #328 and run into any confusions, please ping me on that PR. Even if you resolve it yourself, it’s important that it’s easy to write tests even with the new framework in #328, so I want to improve the docs for that whenever possible, and I’d appreciate hearing about any trouble points. (I already added some docs to that PR but it can be hard to know what’s confusing for a newcomer).

**Comment by ranocha** [comment]
Thanks a lot for your quick and nice answer! I will have a closer look at the code and experiment a bit more before making a PR (probably next week).

**Comment by odow** [comment]
I'm going to close. I've been adding tests https://github.com/jump-dev/Convex.jl/pull/577 and I've found no issues. We could always do more, and we've significantly refactored how we get duals since the original issue was opened.
