### ISSUE TITLE
Ideas for scaling up to large(r) subset selection problems?

### ISSUE THREAD

**Issue by robertfeldt** [jump-dev/Convex.jl#356]
I have previously used a meta-heuristic/black-box optimization approach for large subset selection problems but now exploring if Convex.jl can be used for this. It works great for small problems but when I try to scale this up the optimization times seems to grow exponentially. Any ideas on how to speed this up so can scale to N in the range 500-10000 and M in the range 1000-3000? See below for example with only one constraint, in actual use cases there will be additional constraints of a similar type.

```
using Convex, GLPKMathProgInterface

# Execution times on MacBook Pro 2015 for different N and M:
# 10, 100: 0.005879 secs
# 20, 100: 0.004779
# 50, 100: 0.297040
# 50, 500: 303.723040
N = 50
M = 100

# Which M are covered by each N
MCoveredByN = rand(M, N) .> 0.4

# Problem only feasible if all M can be covered, i.e. at least one N covers an M
feasible = all(c -> c >= 1.0, sum(MCoveredByN, dims=2))

# We want to include (1) or exclude (0) each of the N and minimize the number of selected N.
x = Variable(N, :Bin)
problem = minimize(sum(x), MCoveredByN * x >= 1)
solver = GLPKSolverMIP()
@time solve!(problem, solver)
```

**Comment by ericphanson** [comment]
The first thing I would try is running the code on master. We’ve switched to a MathOptInterface backend and that’s been more performant for other problems (https://github.com/JuliaOpt/Convex.jl/issues/353).

The syntax is the same— currently— the only difference is calling the silver (see eg https://www.juliaopt.org/Convex.jl/dev/examples/mixed_integer/section_allocation/). Note some syntax may change, with deprecations, on master as move towards tagging a breaking release.

**Comment by robertfeldt** [comment]
Thanks, I tried this and see performance improvements on small problem sizes but roughly the same performance for larger examples. Hmm, maybe I need to stay with heuristic optimization for these problems. Any other ideas welcome.

**Comment by odow** [comment]
You could try using JuMP and Cbc. (GLPK isn't the fastest MIP solver.)

```Julia
using JuMP
using Cbc
M, N = 50, 50
MCoveredByN = rand(M, N) .> 0.4
model = Model(with_optimizer(Cbc.Optimizer))
@variable(model, x[1:N], Bin)
@objective(model, Min, sum(x))
@constraint(model, MCoveredByN * x .>= 1)
optimize!(model)
value.(x)
```

**Comment by ericphanson** [comment]
I would hope that Convex.jl on master with the same solver would have similar performance as JuMP, at least for large problems where any overhead in formulation shouldn’t dominate. I’m not sure to what extent that’s true though, so if you end up trying both I’d be interested in hearing the results.

**Comment by odow** [comment]
Closing as out-dated.

For future readers, this sort of question is better posted at the community forum: https://discourse.julialang.org/c/domain/opt/13.
