### ISSUE TITLE
`norm` vs `opnorm` transition should be completed

### ISSUE THREAD

**Issue by ericphanson** [jump-dev/Convex.jl#382]
Right now, if `A` is a matrix, then `norm(A,p)` emits a deprecation warning and calls `opnorm(A,p)`, in line with Julia 0.7. In the next breaking release, we should make `norm(A,p)` call `norm(vec(A), p)` as the deprecation warning states, and remove the warning.

**Comment by ericphanson** [comment]
Step 1: remove `norm(A, p)` for matrices at all, so it produces an error. This will be done in v0.14.0.
Step 2: re-introduce `norm(A, p)` as `norm(vec(A), p)`. This will be done in v0.15.0.

This way, hopefully users will not get incorrect answers if they haven't noticed the deprecation warnings (which are off by default on Julia 1.5+).

**Comment by odow** [comment]
@ericphanson what is the status of this?

**Comment by ericphanson** [comment]
I will put up a PR to finish it
