### ISSUE TITLE
`scaledgeomean` exported but not defined

### ISSUE THREAD

**Issue by ericphanson** [jump-dev/Convex.jl#392]
We have a file https://github.com/jump-dev/Convex.jl/blob/38e5fcce49f34c5d54c925ca5adbfb1979948be8/src/atoms/second_order_cone/scaledgeomean.jl that defines the function, but it never gets included and is not tested. I took a brief look at the git history and couldn't find if it was ever included. We can either include it and test it or take it out.

**Comment by aravindh-krishnamoorthy** [comment]
This seems to be a partial solution to #388 but is not exported. Better to unify this with geomean when updating Convex.jl to MOI. So, the best solution is to leave it as it is and remove it when both this and geomean are changed to use MOI.
