### ISSUE TITLE
Fixing matrix norm and removing deprecation warning

### ISSUE THREAD

**Issue by raphaelchinchilla** [jump-dev/Convex.jl#400]
About 2 years ago, commit #242  aimed to fixed #231 by changing some behaviors and including a deprecation warning. 

Until today, given a matrix M,  norm(M) computes the operator norm instead of the frobenius norm. This behavior is not documented and is not consistent with Julia's.

I suggest finishing commit #242 and deprecate the old behavior. I would do a PR, but I am not familiar enough yet with Julia to feel confident about it

**Comment by ericphanson** [comment]
agreed! (see also https://github.com/jump-dev/Convex.jl/issues/382)

**Comment by ericphanson** [comment]
I'll close this in favor of #382. Step 1 will be done in the imminent v0.14.0 release.
