### ISSUE TITLE
`conj` poisons a variable

### ISSUE THREAD

**Issue by dstahlke** [jump-dev/Convex.jl#416]
Using `conj(X)` seemingly anywhere in a problem does strange things to that variable.  In the below example, the solution does not satisfy the `X == A` constraint.  Instead, we get `X == conj(A)`.

    using Convex, SCS, LinearAlgebra

    A = [1 1im; -1im 1]
    X = ComplexVariable(2, 2)
    p = minimize(real(tr(conj(X))), [X == A])
    solve!(p, () -> SCS.Optimizer(verbose=1, eps=1e-6))
    @show p.status                # OPTIMAL
    @show norm(X.value - A)       # BUG: not equal
    @show norm(X.value - conj(A)) # BUG: equal

**Comment by ericphanson** [comment]
Reminds me of the great old Convex.jl bugs of the past (#279, #280, #284, #381) that got me into this. I had hoped there were no more of those, but glad to fix another. Thanks for reporting!

**Comment by dstahlke** [comment]
Thanks for the fix.  I think complex variables are used by few people, and even then `conj` is pretty rare.  So no surprise it hid for this long.  This came up while porting the Fawzi-Saunderson cvxquad code.
