### ISSUE TITLE
Differentiable convex optimisation problem

### ISSUE THREAD

**Issue by JinraeKim** [jump-dev/Convex.jl#430]
I'm looking for functionality that supports differentiable convex optimisation problem.
For example, making convex problem differentiable by Zygote.jl.

I've heard by @ericphanson that there's a progress on Julia ecosystem for this but it seems not to be mature enough.
I wonder if there's a plan to support the functionality compatible with Convex.jl.

Note that there is an implementation of it in Python as `cvxpylayers`.

Thanks.

**Comment by tjdiamandis** [comment]
See #383 and [DiffOpt.jl](https://github.com/jump-dev/DiffOpt.jl).

DiffOpt.jl is your best bet for the functionality, but it may require some reformulation of your problem.

**Comment by matbesancon** [comment]
I think this can be closed?

**Comment by JinraeKim** [comment]
> I think this can be closed?

Yup, I think so
