### ISSUE TITLE
quadform for positive semi-definite matrices

### ISSUE THREAD

**Issue by JGSuw** [jump-dev/Convex.jl#446]
Hello Convex.jl community,

I am using Julia v1.4 and Convex v0.4.11 and apparently the function `quadform` currently does not support positive semi-definite nor negative semi-definite matrices. This is apparent from [quadform.jl](https://github.com/jump-dev/Convex.jl/blob/master/src/atoms/second_order_cone/quadform.jl) which uses  the `ispodef` routine found in LinearAlgebra.jl to test for positive or negative definiteness.

Unfortunately this restriction is not reflected in the documentation for Convex.jl, which states that to use `quadform` "if _x_ is not constant than _P_ must be symmetric and positive semi-definite". Perhaps the documentation on supported operations was copy/pasted from another language where this functionality is present.

Regardless it is an unfortunate omission, since AFAIK that minimization QPs with positive semi-definite terms in the objective are still convex. Are they still not DCP?

Best,
Joseph Sullivan

**Comment by ericphanson** [comment]
Ah thanks for pointing this out. We actually just changed this code to use `isposdef` in #444 without realising the difference- that’s a bug which we should fix. So try Convex v0.14.10 for now (`] add Convex@0.14.10`). I’d be happy to take a PR to fix the bug, otherwise I can try to get to it in a bit.

**Comment by ericphanson** [comment]
As another workaround, you could also replace the matrix `Q` by `Q + eps*I` for small epsilon. I think that’s probably how we should do the check anyway (ie check if `Q + eps*I` is positive definite).

**Comment by JGSuw** [comment]
Fantastic, thanks for the response. I will use an `eps` term to work around this, I'm glad that it will not actually cause any problems with the solvers.
