### ISSUE TITLE
Example on warmstarting in the manual fails

### ISSUE THREAD

**Issue by hurak** [jump-dev/Convex.jl#451]
The `Advanced` section in the manual contains a [subsection on warmstarting](https://jump.dev/Convex.jl/stable/advanced/#Warmstarting), including an example:

```julia
using Convex
using SCS

# initialize data
n = 1000
y = rand(n)
x = Variable(n)

# first solve
lambda = 100
problem = minimize(sumsquares(y - x) + lambda * sumsquares(x - 10))
@time solve!(problem, SCS.Optimizer)

# now warmstart
# if the solver takes advantage of warmstarts, 
# this run will be faster
lambda = 105
@time solve!(problem, SCS.Optimizer, warmstart=true)
```

(I added the first two lines here in order to make the code self-contained.)

I encouter two issues:

## Warmstarting not supported

The second run of the solver on the very last line of the above code gives 

```julia
julia> @time solve!(problem, SCS.Optimizer, warmstart=true)
┌ Warning: MathOptInterface.VariablePrimalStart() is not supported by SCS.GeometricConicForm{Float64, SCS.SparseMatrixCSRtoCSC{Int64}, NTuple{8, DataType}}. This information will be discarded.
└ @ MathOptInterface.Utilities ~/.julia/packages/MathOptInterface/YDdD3/src/Utilities/copy.jl:290
```
Apparently, warmstarting is actually not present here. 

And indeed, the `solve time`s are comparable in both runs.

## Changed parameter seems to have no impact when solving anew

When running the `solve!` for the second time, it appears that it was also intended to demonstrate how the changed `lambda` parameter (`lambda=105`) is automatically considered when solving the problem as if there was no need to redefine the problem for the new parameter. I suspect the changed parameter is actually not taken into consideration. By making even a more dramatic changed in the parameter `lambda`, I observe no difference in the results. No matter if the warmstarting was (attempted to be) engaged or not:

```julia
lambda = 10000000
@time solve!(problem, SCS.Optimizer, warmstart=true)
```

**Comment by odow** [comment]
Fixed with the latest release of SCS.
