### ISSUE TITLE
Add banner to old versions of Convex.jl docs

### ISSUE THREAD

**Issue by ericphanson** [jump-dev/Convex.jl#460]
Probably using
* https://gist.github.com/pfitzseb/4b910449e21b51fed4b4a2a7c20912ff
*  https://github.com/JuliaDocs/Documenter.jl/pull/1577

to avoid issues like https://discourse.julialang.org/t/is-convex-jl-still-working/68624/5

**Comment by odow** [comment]
Closed by https://github.com/jump-dev/Convex.jl/commit/4db3864d205783c7f0c8e744c1d0961352ea98b6
