### ISSUE TITLE
LASSO/Elastic Net example

### ISSUE THREAD

**Issue by PaulSoderlind** [jump-dev/Convex.jl#485]
at https://jump.dev/Convex.jl/stable/examples/general_examples/lasso_regression/

needs an update after the latest Convex/SCS updates. (See the last figure for why.) I hope to give it a try in a week or so, but please feel welcome to beat me to it.

**Comment by odow** [comment]
What's the problem? The `ALMOST_OPTIMAL` status?

**Comment by PaulSoderlind** [comment]
The gaps in the plot are due to the `ALMOST_OPTIMAL` which in turn seems related to the scaling of the terms in the objective function. (Maybe SCS is now using other convergence criteria, or something. Don't know.) Anyhow, my guess is that an objective function in terms of `X'X/T`  and `X'Y/T` (where T is the number of cases) will be better behaved and also easier to interpret. I'll try later this week.

**Comment by PaulSoderlind** [comment]
The PR (https://github.com/jump-dev/Convex.jl/pull/486) was easy, so I close this issue.
