### ISSUE TITLE
Support for quasiconvex problems

### ISSUE THREAD

**Issue by Uroc327** [jump-dev/Convex.jl#491]
I think support for disciplined quasiconvex programming would fit nicely into this package.

Analogous to disciplined convex programming, there also is the language of disciplined quasiconvex programming [1]. Similar to convex probems, quasiconvex problems have beneficial properties for solving numerically. DQCP is a grammer to describe these problems. Furthermore, quasiconvex problems can be solved using convex methods [1, Section 3], which makes this a suitable part of `Convex.jl`, I believe.

  [1] [https://doi.org/10.1007/s11590-020-01561-8](https://doi.org/10.1007/s11590-020-01561-8)

**Comment by odow** [comment]
Thanks for the suggestion. I'll leave this issue open, but note that this is unlikely to happen due to:
https://github.com/jump-dev/Convex.jl#please-read-convexjl-needs-a-new-maintainer

**Comment by Uroc327** [comment]
I feared as much. But thanks. 

Maybe I find the muse and motivation to implement this myself. Not sure how extensible Convex.jl is in these regards, though. Also not sure whether one wants quasiconvex together with the normal dcp grammar per default or as an explicit extension.

**Comment by odow** [comment]
Closing as won't fix. This is currently beyond the scope of Convex.jl's current maintainers.

Anyone interested should experiment in a fork of Convex.jl and post below if you have something working or have any questions on the implementation.
