### ISSUE TITLE
Does Convex.jl support "Difference of Convex Algorithm (DCA)"?

### ISSUE THREAD

**Issue by JinraeKim** [jump-dev/Convex.jl#497]
DCA refers to optimization algorithms for difference of convex functions.

For example, "basic DCA" introduced in [DC programming and DCA: thirty years of developments](https://link.springer.com/article/10.1007/s10107-018-1235-y), which is basically an iterative algorithm based on convex optimization.

Does Convex.jl support DCA? Or, is there any plan for this?

Thx!

**Comment by odow** [comment]
> Does Convex.jl support DCA?

No to me knowledge.

> Or, is there any plan for this?

No. See https://github.com/jump-dev/Convex.jl#please-read-convexjl-needs-a-new-maintainer

**Comment by odow** [comment]
Closing because there are no plans to add this to Convex.jl.
