### ISSUE TITLE
Relative Entropy Not in Supported Operations Documentation

### ISSUE THREAD

**Issue by mmcelikok** [jump-dev/Convex.jl#499]
Hi,

As far as I can see, relative_entropy.jl means we have KL-divergence (a.k.a. relative entropy) is supported as a DCP atom. But it is not listed anywhere in the docs, also not under Supported Operations.

**Comment by ericphanson** [comment]
Good point, it belongs here: https://jump.dev/Convex.jl/dev/operations/#Exponential-Cone-Representable-Functions

If you or anyone else wants to try adding it, just edit the file [here](https://github.com/jump-dev/Convex.jl/blob/d5e02084dd7a5f7764bf7c738ca9ee8566e26c04/docs/src/operations.md?plain=1#L91) (can click the pencil), and make a pull request.

**Comment by odow** [comment]
Closed by #506
