### ISSUE TITLE
Method overwrite precompilation error on nightly 

### ISSUE THREAD

**Issue by ericphanson** [jump-dev/Convex.jl#507]
> That error isn’t related to your PR, but we will need to fix it. The issue is Convex pirates `hcat` (and I think `hvcat` and `vcat`) by overwriting a method which I suppose now errors. (FYI: I think this can be fixed by switching from the pirate approach to an eval-loop for defining methods for “At least one argument of this type” as in https://www.oxinabox.net/2023/06/17/resident-eval.html).

_Originally posted by @ericphanson in https://github.com/jump-dev/Convex.jl/issues/505#issuecomment-1647682123_

**Comment by odow** [comment]
Closed by https://github.com/jump-dev/Convex.jl/pull/515
