### ISSUE TITLE
Fixing type piracy is becoming more urgent

### ISSUE THREAD

**Issue by KristofferC** [jump-dev/Convex.jl#512]
The type piracy in 

https://github.com/jump-dev/Convex.jl/blob/c6a21df2979dc1eaf60674f7f4b1324a4f30f8b8/src/atoms/affine/stack.jl#L111-L120

causes the package to now error on the 1.10 backport branch https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/4e1759c_vs_0ba6ec2/EnsembleKalmanProcesses.primary.log

```
Failed to precompile Convex [f65535da-76fb-5f13-bab9-19810c17039a] to "/home/pkgeval/.julia/compiled/v1.10/Convex/jl_CmPZEd".
WARNING: Method definition hcat(Union{Number, AbstractArray{T, N} where N where T}...) in module Base at abstractarray.jl:1995 overwritten in module Convex at /home/pkgeval/.julia/packages/Convex/tSTAW/src/atoms/affine/stack.jl:120.
ERROR: LoadError: Method overwriting is not permitted during Module precompile.
Stacktrace:
 [1] top-level scope
   @ ~/.julia/packages/Convex/tSTAW/src/atoms/affine/stack.jl:120
```

**Comment by odow** [comment]
> Method overwriting is not permitted during Module precompile.

This seems like it is a breaking change to Julia then?

**Comment by KristofferC** [comment]
Hm, I don't think so because this should have already printed that this type of method overwriting already is a fatal error, it just didn't hard error for it.

**Comment by odow** [comment]
One issue with fixing this is that it would likely require a breaking change to Convex.jl (e.g., replacing `Base.hcat` with `Convex.hcat`), but https://github.com/jump-dev/Convex.jl#please-read-convexjl-needs-a-new-maintainer.

I guess we have no choice though.

**Comment by KristofferC** [comment]
But isn't the solution here to instead of writing

```julia
 hcat(args::Value...) = Base.cat(args..., dims = Val(2)) 
```

to write something like

```julia
 hcat(arg::Value, args::Value...) = Base.cat((arg, args...)..., dims = Val(2)) 
```

or?

**Comment by odow** [comment]
The issue is:

https://github.com/jump-dev/Convex.jl/blob/c6a21df2979dc1eaf60674f7f4b1324a4f30f8b8/src/expressions.jl#L93

`hcat(arg::Value, args::Value...)` might fix that exact method, but it's still piracy.

**Comment by odow** [comment]
@blegat asks: why is `hcat(args::Value...) = Base.cat(args..., dims = Val(2)) ` even needed?
