### ISSUE TITLE
Constraints Are Not Satisfied for a Simple Quad Form

### ISSUE THREAD

**Issue by RoyiAvital** [jump-dev/Convex.jl#516]
I want to solve:

$$ \arg \min_{\boldsymbol{x}} \frac{1}{2} \boldsymbol{x}^{T} \boldsymbol{A} \boldsymbol{x} \quad \text{ subject to } \quad \boldsymbol{A} \boldsymbol{x} \in {\left[ a, b \right]}^{m} $$

For $\boldsymbol{A} \in \mathbb{R}^{m \times n}$.

The code:

```julia
using Convex;
using ECOS;
using LinearAlgebra;
using SCS;
using StableRNGs;

# Parameters
numRows = 5;
numCols = numRows; #<! PSD Matrix
valA = 0.23;
valB = 1.05;

# Data
oRng = StableRNG(1234);
mA = randn(oRng, numRows, numCols);
mA = mA' * mA;

# DCP Solver
vX0 = Variable(numCols);
sConvProb = minimize(0.5 * quadform(vX0, mA; assume_psd = true), (mA * vX0) <= valB, (mA * vX0) >= valA);
solve!(sConvProb, SCS.Optimizer; silent_solver = true);
```

When I print `vX0` the output is not in the range `[valA, valB]`:

```julia
julia> vX0
Variable
size: (5, 1)
sign: real
vexity: affine
id: 113…069
value: [0.05274385562185869, -3.8296795049800955e-7, -4.796264983535609e-7, 0.26471122629335125, 0.18514752135029242]
```

I tried `ECOS` optimizer as well, with the same results.

**Comment by ericphanson** [comment]
I'm getting
```julia
julia> evaluate(mA * vX0)
5-element Vector{Float64}:
 0.22998236136012307
 0.24591438019531434
 0.5656231835386101
 0.2299921175489734
 0.2300008785611823
```
which is pretty close to right. Solvers will only respect constraints up to some tolerance, see e.g. https://discourse.julialang.org/t/jump-gurobi-binary-variables-end-up-with-values-no-equal-1-or-0/65610/5 (though there's probably a lot more info out there about this).

Is this what you're seeing too, or are you seeing big violations?

**Comment by RoyiAvital** [comment]
I think I made a mistake. 
I looked at the values of `vX0` instead of `mA * vX0`. 

My mistake.
