### ISSUE TITLE
Clarify documentation

### ISSUE THREAD

**Issue by blegat** [jump-dev/Convex.jl#521]
See https://github.com/jump-dev/Convex.jl/pull/504?notification_referrer_id=NT_kwDOAA_-jbI2OTg4NDY4NTE4OjEwNDgyMDU#discussion_r1434608140

**Comment by odow** [comment]
What does this mean

**Comment by ericphanson** [comment]
I believe https://github.com/jump-dev/Convex.jl/pull/504#discussion_r1434608140
