### ISSUE TITLE
Removing Convex.sign and Convex.children

### ISSUE THREAD

**Issue by blegat** [jump-dev/Convex.jl#544]
The user can still use `Base.sign` and `AbstractTrees.children`
See https://github.com/jump-dev/Convex.jl/pull/537#discussion_r1447084648
I think it's fair for `sign`. For `children`, the example in `docs/src/advanced.md` does `using AbstractTrees` anyway.

**Comment by odow** [comment]
I don't actually mind this. It's a bit weird, but at least it's consistent with how we re-export half of LinearAlgebra.

**Comment by odow** [comment]
Closing this as won't fix. I'm okay with leaving this.
