### ISSUE TITLE
Document that atoms must be mutable

### ISSUE THREAD

**Issue by ericphanson** [jump-dev/Convex.jl#548]
In #504 I made all the atoms mutable so that I could use `objectid` for caching. We used to use `hash`, but had performance problems with it (due to recursing through all children for each atom to compute the correct hash), and were vulnerable to hash collisions. I tried removing the cache altogether in earlier commits in #504 but realized it was crucial for performance on larger problems, otherwise we re-create the conic forms many times (possibly due to weird or inefficient traversals?). So I changed all the atoms to be mutable and used an `IdDict`. I think this is reasonable; mutable objects are semantically different from immutable as they are each distinct and have a unique object identity, which I think is the right semantics for our atoms, which basically represent {the conic forms they generate + their children}.

We should document this requirement to help ensure future atoms are all declared mutable. We could possibly design a test for this as well.

As an aside, for most atoms we could make most/all fields `const` on Julia 1.8+.

**Comment by odow** [comment]
For the hash, why is it necessary to recurse through each child? Wouldn't the child cache their hash?

**Comment by ericphanson** [comment]
Caching is tricky bc leaves can change (eg fixed variables) in some ways. Surely there’s a way to do it though. Object identity is nice though for our purposes because we really just want to know is this the exact same object we already computer the conic form for (not, are these two atoms semantically equivalent).

**Comment by odow** [comment]
Ah. I didn't consider leaves being modified in-place.

**Comment by odow** [comment]
#554 adds a test that the atom is mutable.
