### ISSUE TITLE
vexity(::IndexAtom) is inexact

### ISSUE THREAD

**Issue by blegat** [jump-dev/Convex.jl#603]
The `vexity` of the `IndexAtom` is incorrect:
```julia
julia> x = Variable()
Variable
size: (1, 1)
sign: real
vexity: affine
id: 176…085

julia> v = vcat(x, square(x))
reshape (convex; real)
└─ * (convex; real)
   ├─ 2×2 Matrix{Bool}
   └─ reshape (convex; real)
      └─ hcat (convex; real)
         ├─ …
         └─ …

julia> vexity(v)
Convex.ConvexVexity()

julia> vexity(v[1])
Convex.ConvexVexity()

julia> v = vcat(-square(x), square(x))
reshape (Convex.NotDcp; real)
└─ * (Convex.NotDcp; real)
   ├─ 2×2 Matrix{Bool}
   └─ reshape (Convex.NotDcp; real)
      └─ hcat (Convex.NotDcp; real)
         ├─ …
         └─ …

julia> vexity(v)
Convex.NotDcp()

julia> vexity(v[1])
Convex.NotDcp()
```

**Comment by ericphanson** [comment]
The current definition doesn’t depend on the index, it just defers to the object being indexed.  I think it hasn’t come up before since usually all elements in the vector have the same vexity.

**Comment by odow** [comment]
This isn't incorrect so much as inexact: could be improved, but it won't give wrong answers.

**Comment by blegat** [comment]
We discussed this in the JuMP-dev call, the conclusion was that we should try adding a `vcat` atom and specialize `getindex` for the `vcat` atom to try and see if the indices fit in one of the argument in the `vcat` in which case we remove the `vcat` atom and propagage `getindex`
