### ISSUE TITLE
Should GenericConstraint constrain the sets?

### ISSUE THREAD

**Issue by ericphanson** [jump-dev/Convex.jl#630]
It seems each one needs a definition of vexity and head, so plugging an arbitrary set in will give confusing errors to users. Maybe we can check this and give a nicer error? Maybe an allowlist or to be more extensible, we could use hasmethod to try to detect if the set is supported?

**Comment by blegat** [comment]
I'd just add a default method for `vexity(::Vexity, ::MOI.AbstractSet)` that throws a nice error
